Project1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project1.DAL;
using Project1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


    
namespace Project1.Controllers
{
    public class ProductController : Controller
    {
        ProductDAL db = new ProductDAL();
        CartDAL cd = new CartDAL();
        OrderDAL od = new OrderDAL();
        // GET: ProductController
        public ActionResult Index()
        {
            var model = db.GetAllProducts();
            return View(model);
        }
        public ActionResult Products()
        {
            var model = db.GetAllProducts();
            return View(model);
        }


        // GET: ProductController/Details/5
        public ActionResult Details(int Id)
        {
            var model = db.GetProductById(Id);
            return View(model);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                int result = db.AddProduct(product);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int Id)
        {
            var model = db.GetProductById(Id);
            return View(model);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            try
            {
                int result = db.UpdateProduct(product);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = db.GetProductById(id);
            return View(model);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int Id)
        {
            try
            {
                int result = db.DeleteProduct(Id);
                if (result == 1)


                    return RedirectToAction(nameof(Index));
                return View();
            }
            catch
            {
                return View();
            }
        }
       
        public IActionResult AddToCart(int id)
        {
            string Uid = HttpContext.Session.GetString("Uid");
            Cart cart = new Cart();
            cart.Id = id;
            cart.Uid = Convert.ToInt32(Uid);
            int res = cd.AddToCart(cart);
            if (res == 1)
            {
                return RedirectToAction("ViewCart");
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult ViewCart()
        {
            string Uid = HttpContext.Session.GetString("Uid");
            var model = cd.ViewFromCart(Uid);
            return View(model);
        }

        [HttpGet]
        public IActionResult RemoveFromCart(int Cid)
        {
            int res = cd.RemoveFromCart(Cid);
            if (res == 1)
            {
                return RedirectToAction("ViewCart");
            }
            else
            {
                return View();
            }
        }
        public IActionResult ViewProductForOrder(int id)
        {
            string Uid = HttpContext.Session.GetString("Uid");
            Order or = new Order();
            or.Id = id;
            or.Uid = Convert.ToInt32(Uid);
            int res = od.PlaceOrder(or);
            if (res == 1)
            {
                return RedirectToAction("ViewOrder");
            }
            else
            {
                return View();
            }

           

        }
        [HttpGet]
        public IActionResult ViewOrder()
        {
            string Uid = HttpContext.Session.GetString("Uid");
            var model = od.ViewProductForOrder(Uid);
            return View(model);
        }
        [HttpGet]
        public IActionResult RemoveFromOrders(int Oid)
        {
            int res = od.RemoveFromOrders(Oid);
            if (res == 1)
            {
                return RedirectToAction("ViewOrder");
            }
            else
            {
                return View();
            }
        }

    }
}

Project1/Controllers/RegistrationController.cs
  using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project1.DAL;
using Project1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project1.Controllers
{
    public class RegistrationController : Controller
    {

        RegistrationDAL db = new RegistrationDAL();
       
        // GET: RegistrationController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: RegistrationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Registration reg )
        {

            try
            {
                int result = db.Registration(reg);
                if (result == 1)
                    return RedirectToAction(nameof(LogIn));
                else
                    return View();
            }
            
            catch
            {
                return View();
            }
        }

        public IActionResult LogIn()
        {
            return View();
        }

        // POST: LogIn/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LogIn(Registration reg)
        {
            Registration user = db.LogIn(reg);

            if(user.Password== reg.Password)
            {
                HttpContext.Session.SetString("Name", user.EmailId.ToString());
                HttpContext.Session.SetString("Uid", user.Uid.ToString());
                if (user.RoleId ==Roles.Customer)
                    return RedirectToAction("Products", "Product");
                else if (user.RoleId ==Roles.Admin)
                    return RedirectToAction("Index", "Product");
                else
                    return View();

            }
            else
            {
                return View();
            }
            
           
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("LohIn");
        }


    }
}

Project1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!String.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("Uid")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ViewCart">Cart </a>
                            </li>
                            <li class="nav-item" style="padding-left:350px">
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Welcome :@HttpContextAccessor.HttpContext.Session.GetString("Name")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>
                        }
                        @if (String.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("Uid")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="LogIn">Log In </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Create">Registration </a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">   
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Project1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>